# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# User specific aliases and functions
alias l='ls -l'
alias ll='ls -l'

PATH="/usr/local/bin:$PATH" 

# ディストリビューションごとの設定
if [ "$(uname -r | grep MANJARO)" != "" ]; then
  if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
  fi

  alias slp="sudo systemctl hibernate"
fi

# bash completion
for file in git docker docker-compose
do
  [ -e ~/.config/bash_completion.d/${file} ] && . ~/.config/bash_completion.d/${file}
done

if [ ! -f /etc/bash_completion ]; then
  if [ -f ~/.ssh/known_hosts ]; then 
    _yamatomo_known_hosts() {
      local hosts cur prev
     
      hosts=$(cat ~/.ssh/known_hosts | awk '{print $1}')
      cur="${COMP_WORDS[COMP_CWORD]}"
      prev="${COMP_WORDS[COMP_CWORD-1]}"
    
      if [ $COMP_CWORD = 1 ]; then
        COMPREPLY=( $( compgen -W "$hosts"    -- $cur ))
      fi
    }
    complete -F _yamatomo_known_hosts ssh scp
  fi
fi

  
